s=set()
n1=int(input("enter num:"))
n2=int(input("enter num:"))
n3=int(input("enter num:"))
n4=int(input("enter num:"))
n5=int(input("enter num:"))
n6=int(input("enter num:"))
n7=int(input("enter num:"))
n8=int(input("enter num:"))
s.add(n1)
s.add(n2)
s.add(n3)
s.add(n4)
s.add(n5)
s.add(n6)
s.add(n7)
s.add(n8)
print(s)